language: elixir
matrix:
  include:
    - otp_release: 18.3
      elixir: 1.4
    - otp_release: 19.3
      elixir: 1.4
sudo: false
env:
  - ELIXIR_ASSERT_TIMEOUT=2000
before_script:
  - psql -c "CREATE ROLE elixir WITH LOGIN PASSWORD 'elixir' CREATEDB CREATEROLE;" -U postgres
  - mix deps.get
  - nvm install 6.2 && nvm use 6.2
script:
  - mix test